### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by pointofpresence** [TommyX12/music-copilot#1]
FL Studio 2024.1

Traceback (most recent call last):
file: <string> apply line: 619
file: <string> run line: 544
file: <string> query_llm line: 403
file: subprocess.py __init__ line: 992
file: subprocess.py _get_handles line: 1350
SystemError (<built-in function CreatePipe> returned NULL without setting an exception)

**Comment by TommyX12** [comment]
I haven't tested this script with 2024.1 yet. It's possible that they don't support subprocess anymore... Maybe need to find another way to get this to work.

**Comment by neldivad** [comment]
I have the same problem. Python added to windows base path, pip installed openai. Tried to run a script directly from CMD

using FL 2024

```
C:\Users\David>python "C:/Program Files/Image-Line/FL Studio 2024/System/Config/Piano roll scripts/music-copilot-main/music_copilot_helper.py" '{"prompt":"test","api_key":"sk-","model":"gpt-3.5-turbo"}'

ERROR
Traceback (most recent call last):
  File "C:\Program Files\Image-Line\FL Studio 2024\System\Config\Piano roll scripts\music-copilot-main\music_copilot_helper.py", line 4, in <module>
    from openai import OpenAI
ModuleNotFoundError: No module named 'openai'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Image-Line\FL Studio 2024\System\Config\Piano roll scripts\music-copilot-main\music_copilot_helper.py", line 24, in <module>
    traceback.print_exc()
    ^^^^^^^^^
NameError: name 'traceback' is not defined

C:\Users\David>pip list
Package           Version
----------------- ----------
annotated-types   0.7.0
anyio             4.8.0
certifi           2024.12.14
colorama          0.4.6
distro            1.9.0
h11               0.14.0
httpcore          1.0.7
httpx             0.28.1
idna              3.10
jiter             0.8.2
openai            1.60.1
pip               24.3.1
pydantic          2.10.6
pydantic_core     2.27.2
sniffio           1.3.1
tqdm              4.67.1
typing_extensions 4.12.2
```
